---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: false

platforms:
  - name: cumulus-vx-2.5.6
    driver:
      box: cumulus-vx-2.5.6
      provision: true
      vagrantfiles: ['test/provision-chef.rb']

suites:
  - name: default
    run_list:
      - recipe[cumulus]
      - recipe[cumulus-test]
